receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:
      paging:
      processes:

exporters:
  prometheus:
    endpoint: '0.0.0.0:8889'

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [prometheus]
